rule trimal :
    input :
        alignment='{sample}.fa',  # Input alignment file
    output:
        alignment='{sample}.nwk',  # Output tree file
    log:
        'logs/muscle/{sample}.log',
    params:
        extra='',  # Additional arguments
    wrapper:
        'master/bio/trimal'
