rule clustalo:
    input:
        "{sample}.fa"
    output:
        "{sample}.msa.fa"
    params:
        extra=""
    log:
        "logs/mafft/test/{sample}.log"
    threads: 8
    wrapper:
        "master/bio/mafft"
